export type UserRole = "entrepreneur" | "provider";

export interface User {
  email: string;
  name?: string;
  avatarUrl?: string;
  role?: UserRole;
}

export type ProviderKind = "abogado" | "contador" | "asesor-financiero" | "marketing" | "gestoria" | "insumos";

export interface ProviderProfile {
  name: string;
  kind: ProviderKind;
  isAI?: boolean;
  city: string;
  country: string;
  description: string;
  helpsWith: string[];
}

export interface TeamRecommendation {
  providerId: string;
  reason: string;
  forStepId?: string;
}

export type BusinessCategory =
  | "cafeteria"
  | "restaurante"
  | "tienda-abarrotes"
  | "salon-belleza"
  | "taller-mecanico"
  | "papeleria"
  | "otro";

export interface BusinessFormData {
  businessType: string;
  category: BusinessCategory;
  budget: number;
  location: {
    country: "Mexico" | "Colombia" | "Argentina" | "Chile" | "Peru" | "Otro";
    state: string;
    city: string;
  };
  experience: "ninguna" | "poca" | "intermedia" | "experto";
  /** Free-text description the entrepreneur writes about their idea — the
   * concept, target customer, what makes it different. Sent to the AI so
   * its reading of the market and its team recommendations account for
   * the actual business, not just its category. */
  description?: string;
}

export type ProfileVisibility = "private" | "business" | "profile";

export interface DataPreferences {
  visibility: ProfileVisibility;
  locationPrecision: "city" | "zone";
  onboardingComplete: boolean;
  selectedZoneId?: string;
  /** Exact point the owner chose for a local analysis. It is private and is
   * never included in matching or community payloads. */
  selectedLocation?: { lat: number; lng: number; label?: string };
  locationMode?: "explore" | "existing";
  /** Whether the user has dismissed the "how this works" tutorial banner. */
  tutorialSeen?: boolean;
}

export interface ReportSource {
  name: string;
  publisher: string;
  year: number;
  url: string;
}

export interface ReportData {
  sectorGrowthPercent: number;
  sectorGrowthPeriod: string;
  localBusinessCount: number;
  avgMonthlyRevenue: number;
  survivalRate5Years: number;
  demandTrend: "creciendo" | "estable" | "decreciendo";
  insights: string[];
  sources: ReportSource[];
  /** "llm": generated by the model from the real OSM count + this business's
   * own form. "fallback": the model was unavailable, so a local heuristic
   * filled in — still seeded by the real count when Overpass answered. */
  source: "llm" | "fallback";
  /** Whether localBusinessCount actually came from OpenStreetMap this time
   * (vs. defaulting to 0 because Overpass didn't answer). */
  osmAvailable: boolean;
  /** Source of the real local-offer count. Kept optional for reports saved
   * before the DENUE integration. */
  marketSource?: "inegi_denue_snapshot" | "openstreetmap" | string | null;
}

export type StepStatus = "locked" | "available" | "in-progress" | "completed";

export type StepCategory = "legal" | "mentoria" | "finanzas" | "marketing" | "operaciones" | "escalamiento";

export interface RoadmapStep {
  id: string;
  level: number;
  title: string;
  description: string;
  category: StepCategory;
  status: StepStatus;
  xp: number;
  detail: StepDetail;
}

export interface StepDetail {
  summary: string;
  instructions: string[];
  applicability: "base" | "conditional" | "recommended";
  authority: string;
  evidence: string[];
  officialLinks: { label: string; url: string }[];
  caution?: string;
  hasCost: boolean;
  estimatedCost?: string;
  canDoOnline: boolean;
  connectTo?: ("mentores" | "proveedores")[];
}

export interface Mentor {
  id: string;
  name: string;
  expertise: string;
  businessesOpened: number;
  location: string;
  rating: number;
  avatarColor: string;
}

export interface Provider {
  id: string;
  name: string;
  kind: ProviderKind;
  isAI?: boolean;
  isDemo?: boolean;
  category: string;
  type: "producto" | "servicio";
  location: string;
  city: string;
  rating: number;
  description: string;
  helpsWith: string[];
}

export interface CommunityMessage {
  id: string;
  author: string;
  location: string;
  businessType: string;
  message: string;
  timestamp: string;
}

export interface ZoneMetrics {
  id: string;
  name: string;
  row: number;
  col: number;
  supply: number; // 0-100: cuántos negocios similares ya existen (más alto = más saturado)
  demand: number; // 0-100: qué tanta gente busca este tipo de negocio
  cost: number; // 0-100: costo relativo de renta/operación
  opportunityScore: number; // 0-100: derivado de demanda alta, oferta baja, costo manejable
}

export interface HeatmapData {
  centerLabel: string;
  zones: ZoneMetrics[];
}

export interface UserProgress {
  level: number;
  xp: number;
  completedSteps: string[];
  lastActiveAt: string;
}
